# Generated by Django 5.1.5 on 2025-02-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_livro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='imagem',
        ),
    ]
